insert into Schools (name, location, division, conference) values ('Kihn LLC', 'Kandava', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Lubowitz Inc', 'Qingxi', 2, 'AAC');
insert into Schools (name, location, division, conference) values ('Lockman, Nitzsche and Ankunding', 'Voyinka', 2, 'AAC');
insert into Schools (name, location, division, conference) values ('Keebler, Herzog and Casper', 'Liloan', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Ruecker LLC', 'Capayán', 2, 'Big East');
insert into Schools (name, location, division, conference) values ('Wunsch-Schoen', 'Dianwan', 3, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Prohaska Group', 'Sanjinquan', 3, 'WCC');
insert into Schools (name, location, division, conference) values ('Koepp, Reilly and Tremblay', 'Fengyi', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('Kuphal, Murray and Rempel', 'Sainte-Geneviève-des-Bois', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Leannon-Rice', 'Les Cèdres', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Abernathy-Heaney', 'Draginje', 1, 'WCC');
insert into Schools (name, location, division, conference) values ('Kreiger-O''Keefe', 'Graksop', 1, 'ACC');
insert into Schools (name, location, division, conference) values ('Boyle-Zieme', 'Acolla', 1, 'ACC');
insert into Schools (name, location, division, conference) values ('Carroll, Frami and Harvey', 'Oslo', 2, 'Big 12');
insert into Schools (name, location, division, conference) values ('Schoen-Lind', 'Gulyantsi', 2, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Douglas-Raynor', 'Atamyrat', 1, 'SEC');
insert into Schools (name, location, division, conference) values ('Jenkins and Sons', 'Kafr Mandā', 1, 'WCC');
insert into Schools (name, location, division, conference) values ('Torphy Inc', 'Huangsha', 3, 'Big 12');
insert into Schools (name, location, division, conference) values ('Schultz and Sons', 'Zavety Ilicha', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('O''Hara-Reichel', 'Luis Donaldo Colosio', 1, 'A-10');
insert into Schools (name, location, division, conference) values ('Cassin-Prosacco', 'Olonets', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('Metz LLC', 'Ebebiyin', 2, 'WCC');
insert into Schools (name, location, division, conference) values ('Hane-Koepp', 'Trelleborg', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('Prohaska Inc', 'Sunja', 3, 'Big 12');
insert into Schools (name, location, division, conference) values ('Gleason, Thiel and Willms', 'Góra', 3, 'WCC');
insert into Schools (name, location, division, conference) values ('Koch and Sons', 'Mabayo', 2, 'AAC');
insert into Schools (name, location, division, conference) values ('McLaughlin, Koss and Flatley', 'Mnich', 1, 'WCC');
insert into Schools (name, location, division, conference) values ('Bosco Inc', 'Haiyan', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Reilly-Doyle', 'Pak Thong Chai', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Bernier, Jacobson and Green', 'Dallas', 2, 'AAC');
insert into Schools (name, location, division, conference) values ('Schultz, Jacobi and Schultz', 'Skeldon', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Grady, Gerlach and Ritchie', 'Pantang', 3, 'Big East');
insert into Schools (name, location, division, conference) values ('Cassin-Nienow', 'Ar Riqqah', 3, 'WCC');
insert into Schools (name, location, division, conference) values ('Dooley-Ferry', 'Usuki', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Cormier LLC', 'La Sabana', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('Abbott, Adams and Lueilwitz', 'Göteborg', 3, 'A-10');
insert into Schools (name, location, division, conference) values ('Turcotte-Wolff', 'Rio', 3, 'Big Ten');
insert into Schools (name, location, division, conference) values ('O''Connell, Howell and Klocko', 'Hidalgo', 1, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Harris Inc', 'Pnikut', 2, 'ACC');
insert into Schools (name, location, division, conference) values ('McCullough, Schultz and Bogisich', 'Youxi', 2, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Lindgren-Streich', 'Erniusuokou', 3, 'WCC');
insert into Schools (name, location, division, conference) values ('Berge and Sons', 'Pasar', 3, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Collier, O''Conner and Metz', 'Libato', 2, 'WCC');
insert into Schools (name, location, division, conference) values ('Schamberger, Friesen and Schamberger', 'Ad Dawādimī', 2, 'Big East');
insert into Schools (name, location, division, conference) values ('Price Group', 'Seymchan', 1, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Mraz, Cummings and Pfannerstill', 'Shencang', 2, 'WCC');
insert into Schools (name, location, division, conference) values ('Koch, Koelpin and Schimmel', 'Tessaoua', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('Hamill, Kohler and Will', 'Hernando', 2, 'Big 12');
insert into Schools (name, location, division, conference) values ('Breitenberg, Sporer and Beatty', 'Bugulma', 2, 'WCC');
insert into Schools (name, location, division, conference) values ('Dach, Hand and Herzog', 'Segong', 3, 'AAC');
insert into Schools (name, location, division, conference) values ('Keebler-Orn', 'Stamboliyski', 2, 'Big 12');
insert into Schools (name, location, division, conference) values ('Carroll, Pfannerstill and Farrell', 'Liulin', 2, 'WCC');
insert into Schools (name, location, division, conference) values ('Heaney-Koelpin', 'Ar Ruḩaybah', 2, 'ACC');
insert into Schools (name, location, division, conference) values ('Schuppe LLC', 'Selaawi', 1, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Auer, Casper and Kshlerin', 'Yarmolyntsi', 2, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Dooley, Willms and Cummings', 'Phon Phisai', 1, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Wolff Group', 'Kiukainen', 1, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Bergnaum-Hauck', 'Mandangoa', 2, 'Big 12');
insert into Schools (name, location, division, conference) values ('Reichel-Dicki', 'Luoping', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Maggio, Weber and Altenwerth', 'Columbia', 3, 'Big East');
insert into Schools (name, location, division, conference) values ('Bogan, Kunze and Haag', 'Zhukeng', 1, 'A-10');
insert into Schools (name, location, division, conference) values ('Gleason LLC', 'Tīrān', 2, 'ACC');
insert into Schools (name, location, division, conference) values ('Lakin Group', 'Kawengan', 2, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Medhurst-Nader', 'Fort Macleod', 3, 'AAC');
insert into Schools (name, location, division, conference) values ('Parker-Pollich', 'Oula Xiuma', 3, 'SEC');
insert into Schools (name, location, division, conference) values ('Kemmer and Sons', 'Mgachi', 1, 'A-10');
insert into Schools (name, location, division, conference) values ('Schoen-Wilderman', 'Tây Ninh', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('McGlynn, Labadie and Fay', 'Albany', 2, 'ACC');
insert into Schools (name, location, division, conference) values ('Dickinson LLC', 'Tengah', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Block Group', 'Khānewāl', 2, 'Big 12');
insert into Schools (name, location, division, conference) values ('Hintz, Kovacek and Ledner', 'Kubachi', 1, 'WCC');
insert into Schools (name, location, division, conference) values ('Borer and Sons', 'Mpumalanga', 3, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Jaskolski Inc', 'Tynne', 2, 'Big East');
insert into Schools (name, location, division, conference) values ('Mohr, Klein and Hamill', 'Jelisavac', 2, 'Big East');
insert into Schools (name, location, division, conference) values ('Ortiz Group', 'Texistepeque', 2, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Parisian Group', 'Río Ceballos', 3, 'Big 12');
insert into Schools (name, location, division, conference) values ('Lind, Pfannerstill and Bergnaum', 'Gununganyar', 3, 'Big East');
insert into Schools (name, location, division, conference) values ('Yost, Morar and Flatley', 'Ujung', 1, 'ACC');
insert into Schools (name, location, division, conference) values ('Carroll, Goodwin and O''Conner', 'Horodok', 2, 'ACC');
insert into Schools (name, location, division, conference) values ('Turcotte, Romaguera and Cassin', 'Falun', 2, 'AAC');
insert into Schools (name, location, division, conference) values ('Schoen Inc', 'Dao', 3, 'A-10');
insert into Schools (name, location, division, conference) values ('Leannon LLC', 'Tabālah', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Torp Inc', 'Shitang', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Feeney-Yundt', 'Nartkala', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('Waelchi and Sons', 'Angoulême', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('Jenkins Inc', 'Killumney', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Welch-Runolfsdottir', 'Samut Songkhram', 2, 'WCC');
insert into Schools (name, location, division, conference) values ('Marvin Inc', 'Sypniewo', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('Dicki-Romaguera', 'Taibao', 2, 'AAC');
insert into Schools (name, location, division, conference) values ('DuBuque-Windler', 'Dayr as Sūdān', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Rutherford Group', 'Kipit', 3, 'SEC');
insert into Schools (name, location, division, conference) values ('Altenwerth-Botsford', 'Paris 07', 3, 'A-10');
insert into Schools (name, location, division, conference) values ('McClure-Tremblay', 'Wensu', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Welch-Weissnat', 'Liangshui', 1, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Mueller Inc', 'Zvenigorod', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Nienow, Russel and Yost', 'Malesína', 2, 'AAC');
insert into Schools (name, location, division, conference) values ('Ernser LLC', 'Metz', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('Bogan-Kshlerin', 'Baitu', 2, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Gulgowski-Abbott', 'Skwierzyna', 3, 'A-10');
insert into Schools (name, location, division, conference) values ('Stehr, Schowalter and Nicolas', 'Lueng Putu', 3, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Murray, Schowalter and Shanahan', 'Ichupampa', 2, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Jerde-Von', 'Otyń', 1, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Larson Inc', 'Nazarje', 2, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Reinger-Mante', 'Ol Kalou', 1, 'SEC');
insert into Schools (name, location, division, conference) values ('Murphy-Dibbert', 'Hushi', 3, 'A-10');
insert into Schools (name, location, division, conference) values ('Herzog Inc', 'Goussainville', 2, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Casper Group', 'Põlva', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Kunde Group', 'Düsseldorf', 1, 'A-10');
insert into Schools (name, location, division, conference) values ('Schamberger, Hartmann and Gerlach', 'Großklein', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Nitzsche-Buckridge', 'Huangdu', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('Lebsack Group', 'Līgatne', 3, 'Big 12');
insert into Schools (name, location, division, conference) values ('Donnelly, Krajcik and Streich', 'Anyu', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('Abshire-Zboncak', 'Pantai', 2, 'AAC');
insert into Schools (name, location, division, conference) values ('Kunze, DuBuque and Johnston', 'Bancar', 2, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Gottlieb-Romaguera', 'Nelspruit', 2, 'SEC');
insert into Schools (name, location, division, conference) values ('Raynor Group', 'Luleå', 1, 'A-10');
insert into Schools (name, location, division, conference) values ('Armstrong-Fisher', 'Brant', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Mosciski LLC', 'Sacramento', 2, 'Big 12');
insert into Schools (name, location, division, conference) values ('Hickle-Kutch', 'Sizao', 3, 'Big East');
insert into Schools (name, location, division, conference) values ('Watsica, Mosciski and Zemlak', 'Castrovirreyna', 1, 'A-10');
insert into Schools (name, location, division, conference) values ('Keebler, Corkery and Mertz', 'Thị Trấn Cẩm Thủy', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('Bins-Gusikowski', 'Kukushtan', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('VonRueden-Breitenberg', 'Pápa', 3, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Prosacco, Predovic and Kovacek', 'Distracción', 1, 'ACC');
insert into Schools (name, location, division, conference) values ('Feil-Hartmann', 'Kota Kinabalu', 2, 'ACC');
insert into Schools (name, location, division, conference) values ('McKenzie and Sons', 'Salvacion', 2, 'SEC');
insert into Schools (name, location, division, conference) values ('Mitchell, Sawayn and Volkman', 'Oranmore', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Abshire, Hirthe and Medhurst', 'Jiekou', 1, 'SEC');
insert into Schools (name, location, division, conference) values ('Pagac and Sons', 'Lanlacuni Bajo', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('Hirthe Group', 'Kimry', 2, 'AAC');
insert into Schools (name, location, division, conference) values ('Bruen Inc', 'Tanalt', 3, 'WCC');
insert into Schools (name, location, division, conference) values ('Langosh-Moore', 'Zalishchyky', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Baumbach-Hermann', 'Revda', 1, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Torp-Anderson', 'Novotroitskaya', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Armstrong and Sons', 'Calvos', 3, 'WCC');
insert into Schools (name, location, division, conference) values ('Kuhn Group', 'Magaozhuang', 3, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Gibson-Kub', 'Zhangshi', 3, 'AAC');
insert into Schools (name, location, division, conference) values ('Collier Group', 'Bandhagen', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Rowe, Donnelly and Powlowski', 'Řehlovice', 2, 'Big East');
insert into Schools (name, location, division, conference) values ('Adams-Barrows', 'San Juan', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Weimann Group', 'Tabwakea Village', 3, 'SEC');
insert into Schools (name, location, division, conference) values ('Mante, Auer and Kassulke', 'Xianyan', 1, 'SEC');
insert into Schools (name, location, division, conference) values ('Reichert-Kessler', 'Bariri', 3, 'WCC');
insert into Schools (name, location, division, conference) values ('Halvorson, Rippin and Towne', 'Arauá', 3, 'Big East');
insert into Schools (name, location, division, conference) values ('Dickinson LLC', 'Daxing', 3, 'WCC');
insert into Schools (name, location, division, conference) values ('Funk, Grant and Wilkinson', 'Bački Petrovac', 2, 'SEC');
insert into Schools (name, location, division, conference) values ('Heathcote-Hahn', 'Jiangcun', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Hamill, Turner and Hintz', 'Shamanka', 2, 'Big East');
insert into Schools (name, location, division, conference) values ('Ward-Leuschke', 'Ordzhonikidzevskaya', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Senger, Gibson and Walker', 'Itapecerica da Serra', 1, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Kunde, Skiles and Nienow', 'Três Coroas', 2, 'AAC');
insert into Schools (name, location, division, conference) values ('Nader-Walsh', 'Bucheon-si', 1, 'SEC');
insert into Schools (name, location, division, conference) values ('Bogan Inc', 'Sabaneta', 3, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Cummings, Kris and Okuneva', 'Thị Trấn Pác Miầu', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('Fay and Sons', 'An Châu', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Cruickshank LLC', 'Novokuybyshevsk', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Sipes-Gleichner', 'Murowana Goślina', 2, 'Big 12');
insert into Schools (name, location, division, conference) values ('Feil-Cummerata', 'Caikouji', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Bogisich-Breitenberg', 'Zall-Dardhë', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Mohr, Wunsch and Harris', 'Qingshui', 3, 'SEC');
insert into Schools (name, location, division, conference) values ('Wisoky-Jacobi', 'Caibarién', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Keebler, Muller and Murphy', 'Shiyun', 3, 'SEC');
insert into Schools (name, location, division, conference) values ('West-Bednar', 'Novovarshavka', 3, 'SEC');
insert into Schools (name, location, division, conference) values ('Huel, Parisian and Rowe', 'Szynwałd', 3, 'Big East');
insert into Schools (name, location, division, conference) values ('Pacocha-Gottlieb', 'Yinkeng', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('Baumbach, Treutel and Willms', 'Traiguén', 3, 'Big East');
insert into Schools (name, location, division, conference) values ('Gutkowski-Maggio', 'Chicago', 3, 'ACC');
insert into Schools (name, location, division, conference) values ('Powlowski, Willms and Durgan', 'Popayán', 2, 'WCC');
insert into Schools (name, location, division, conference) values ('Bernier-Koss', 'Saint Aubin', 3, 'SEC');
insert into Schools (name, location, division, conference) values ('Reichert-Schuppe', 'Dongyu', 3, 'Big East');
insert into Schools (name, location, division, conference) values ('Prosacco and Sons', 'Malvas', 3, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Schuster-Schmitt', 'Oslo', 3, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Doyle LLC', 'Murici', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('DuBuque Inc', 'Tasböget', 3, 'Big East');
insert into Schools (name, location, division, conference) values ('Kshlerin LLC', 'Paghmān', 1, 'WCC');
insert into Schools (name, location, division, conference) values ('Mayert LLC', 'Aqqan', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Hodkiewicz and Sons', 'Wielgie', 2, 'ACC');
insert into Schools (name, location, division, conference) values ('Grant, Keeling and Ernser', 'Labuhan Deli', 3, 'Big 12');
insert into Schools (name, location, division, conference) values ('Lockman Inc', 'Salamá', 2, 'Big East');
insert into Schools (name, location, division, conference) values ('Feest and Sons', 'Матејче', 3, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Swift Group', 'Maliuzui', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Ledner and Sons', 'Miguel Hidalgo', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Jacobs-Mueller', 'Cerro de Pasco', 1, 'A-10');
insert into Schools (name, location, division, conference) values ('Russel-Bins', 'Gaotai', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Pacocha Inc', 'Krajan Pangkah Kulon', 3, 'WCC');
insert into Schools (name, location, division, conference) values ('Zboncak Group', 'Proástion', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('Buckridge, Ortiz and Nicolas', 'Malabang', 2, 'ACC');
insert into Schools (name, location, division, conference) values ('Bahringer, Windler and Osinski', 'Jablunkov', 3, 'Big 12');
insert into Schools (name, location, division, conference) values ('Cummerata and Sons', 'Pinrang', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Trantow, Feeney and Abernathy', 'Gaokan', 1, 'A-10');
insert into Schools (name, location, division, conference) values ('Volkman and Sons', 'Cirateun', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Kling and Sons', 'Quế Sơn', 3, 'SEC');
insert into Schools (name, location, division, conference) values ('Kreiger Inc', 'Islāmkot', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('Schimmel-Stamm', 'Pôsto Fiscal Rolim de Moura', 3, 'Big East');
insert into Schools (name, location, division, conference) values ('Davis, Keebler and Hills', 'Santa Eulalia', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Kuhn Group', 'Kafr ad Dawwār', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Prohaska Inc', 'Al Qamşīyah', 3, 'A-10');
insert into Schools (name, location, division, conference) values ('Kris-Boyer', 'Ambatolampy', 2, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Terry-Pagac', 'Barbaza', 3, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Leffler-Mraz', 'Banxi', 2, 'SEC');
insert into Schools (name, location, division, conference) values ('Donnelly-Hyatt', 'Meneou', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('Bosco Inc', 'Isla Verde', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('Hudson-Jacobson', 'Kodinsk', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Effertz-Wunsch', 'Paris 14', 2, 'ACC');
insert into Schools (name, location, division, conference) values ('Herzog LLC', 'Dagang', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Lind, Abernathy and Quitzon', 'Presidente Bernardes', 2, 'SEC');
insert into Schools (name, location, division, conference) values ('Wuckert-Jacobson', 'Trieste', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Morar, Daniel and Smitham', 'Sri Jayewardenepura Kotte', 3, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Schamberger LLC', 'Qiaotou', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Turcotte, Carter and Sanford', 'Chinju', 3, 'SEC');
insert into Schools (name, location, division, conference) values ('Block Inc', 'Santo Rosario', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('Kuhlman, Klocko and Dibbert', 'Dzüyl', 1, 'ACC');
insert into Schools (name, location, division, conference) values ('Metz and Sons', 'Tabon', 1, 'SEC');
insert into Schools (name, location, division, conference) values ('Anderson LLC', 'Daulatpur', 1, 'SEC');
insert into Schools (name, location, division, conference) values ('Towne Group', 'Columbus', 1, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Kulas, Wilderman and Nolan', 'Ágios Vasíleios', 2, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Koelpin-Frami', 'Cisasak', 3, 'ACC');
insert into Schools (name, location, division, conference) values ('Sauer, Robel and Dibbert', 'Los Mangos', 1, 'WCC');
insert into Schools (name, location, division, conference) values ('Wolf Group', 'Veverská Bítýška', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Doyle, Kemmer and Franecki', 'Toulon', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Bechtelar, Strosin and McCullough', 'Guxian', 1, 'A-10');
insert into Schools (name, location, division, conference) values ('Carter, Muller and O''Conner', 'Montbéliard', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('O''Connell Group', 'Horizonte', 2, 'Big East');
insert into Schools (name, location, division, conference) values ('Connelly-Wilderman', 'Qingshuihe', 1, 'SEC');
insert into Schools (name, location, division, conference) values ('Toy-Ferry', 'Świebodzice', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Skiles LLC', 'Kapenguria', 1, 'ACC');
insert into Schools (name, location, division, conference) values ('Kerluke, Treutel and Becker', 'Benito Juarez', 3, 'WCC');
insert into Schools (name, location, division, conference) values ('Kuhic, Collier and Pacocha', 'Krokeaí', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Deckow LLC', 'Cerro Corá', 3, 'Big East');
insert into Schools (name, location, division, conference) values ('Stamm-Harris', 'Nanping', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Hodkiewicz, Stoltenberg and Gerhold', 'Lazo', 3, 'WCC');
insert into Schools (name, location, division, conference) values ('Batz and Sons', 'Tanjung Pandan', 3, 'AAC');
insert into Schools (name, location, division, conference) values ('Murray-Kohler', 'Huayuan', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Bauch-Kshlerin', 'Majāz al Bāb', 2, 'WCC');
insert into Schools (name, location, division, conference) values ('Haley Group', 'Longxing', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Boyer, Bechtelar and Rath', 'Bamiantong', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Quigley, Kuhlman and Rath', 'Saraktash', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Gerhold-Gutmann', 'Xinli', 2, 'Big East');
insert into Schools (name, location, division, conference) values ('Nader-Spencer', 'Higashine', 1, 'Big East');
insert into Schools (name, location, division, conference) values ('Hudson Inc', 'København', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('Turcotte, Oberbrunner and Herman', 'Xiliu', 1, 'WCC');
insert into Schools (name, location, division, conference) values ('Leffler-Kertzmann', 'Benito Juarez', 2, 'Big 12');
insert into Schools (name, location, division, conference) values ('Altenwerth-Hessel', 'Kuje', 3, 'SEC');
insert into Schools (name, location, division, conference) values ('Wuckert Group', 'Futu', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('O''Reilly, Corwin and Gislason', 'Huazhuang', 1, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Boehm, Hintz and Hilll', 'Stepnogorsk', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('Gislason, Cruickshank and Ritchie', 'Sicaya', 1, 'A-10');
insert into Schools (name, location, division, conference) values ('Harris LLC', 'Ngembel', 1, 'SEC');
insert into Schools (name, location, division, conference) values ('Rempel-Bartell', 'Silodakon', 3, 'ACC');
insert into Schools (name, location, division, conference) values ('King, Dietrich and Nienow', 'Fukuechō', 1, 'WCC');
insert into Schools (name, location, division, conference) values ('Beahan-Witting', 'Kedungwaru', 3, 'A-10');
insert into Schools (name, location, division, conference) values ('Buckridge-Ebert', 'Banyubang', 2, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Legros and Sons', 'Witbank', 3, 'AAC');
insert into Schools (name, location, division, conference) values ('VonRueden, Volkman and Wilkinson', 'Taiping', 2, 'Big 12');
insert into Schools (name, location, division, conference) values ('Zulauf Inc', 'Mhlambanyatsi', 1, 'ACC');
insert into Schools (name, location, division, conference) values ('Homenick, Koelpin and Howe', 'Changfu', 2, 'WCC');
insert into Schools (name, location, division, conference) values ('Nader LLC', 'Handan', 2, 'AAC');
insert into Schools (name, location, division, conference) values ('Beer, Abshire and Kunde', 'Krajan', 3, 'ACC');
insert into Schools (name, location, division, conference) values ('Harris-O''Conner', '''Ali Sabieh', 1, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Dach, Huels and Senger', 'Cigaras', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Bartoletti and Sons', 'Suchań', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Torphy-Wisozk', 'Yacuiba', 3, 'AAC');
insert into Schools (name, location, division, conference) values ('Balistreri, Hoppe and Ryan', 'Djohong', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Howe, Skiles and Hilll', 'Louis Trichardt', 3, 'WCC');
insert into Schools (name, location, division, conference) values ('Koss and Sons', 'Ibaiti', 1, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Conroy, Jacobs and Hyatt', 'Simitli', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('Brakus and Sons', 'Karengan', 3, 'SEC');
insert into Schools (name, location, division, conference) values ('Stehr Inc', 'Congonhas', 2, 'Big 12');
insert into Schools (name, location, division, conference) values ('Kuhlman LLC', 'Harrismith', 3, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Parker, West and Cassin', 'Shizong', 3, 'Big East');
insert into Schools (name, location, division, conference) values ('Dickens-White', 'Prilep', 3, 'A-10');
insert into Schools (name, location, division, conference) values ('Muller-O''Reilly', 'Feodosiya', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Yundt-Huel', 'Zbąszynek', 3, 'AAC');
insert into Schools (name, location, division, conference) values ('Vandervort-Stoltenberg', 'Ferreiros', 2, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Zboncak, Boyer and Sporer', 'Ignacio Zaragoza', 2, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Bailey-Weimann', 'Daxindian', 2, 'AAC');
insert into Schools (name, location, division, conference) values ('Runolfsson-Farrell', 'Viking', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('Schuster and Sons', 'Karangtengah Lor', 1, 'Big 12');
insert into Schools (name, location, division, conference) values ('Kunze and Sons', 'Sepulu', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Goyette-Fisher', 'Rudka', 3, 'Big 12');
insert into Schools (name, location, division, conference) values ('Gerlach-Beer', 'Puerto Nariño', 2, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Nader, Ryan and Reinger', 'Maymana', 2, 'Big 12');
insert into Schools (name, location, division, conference) values ('Rohan Inc', 'Takahashi', 3, 'ACC');
insert into Schools (name, location, division, conference) values ('Collier-Fahey', 'Boé', 1, 'Big Ten');
insert into Schools (name, location, division, conference) values ('Goodwin, Stanton and Casper', 'Shiguai', 1, 'ACC');
insert into Schools (name, location, division, conference) values ('Ledner and Sons', 'Urus-Martan', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Friesen, Harber and Collier', 'Kimry', 3, 'WCC');
insert into Schools (name, location, division, conference) values ('Rice, Batz and Schaden', 'Hengfan', 3, 'ACC');
insert into Schools (name, location, division, conference) values ('Stamm, Kerluke and Blanda', 'Vavoua', 3, 'Big East');
insert into Schools (name, location, division, conference) values ('Weissnat-Breitenberg', 'Centenary', 2, 'WCC');
insert into Schools (name, location, division, conference) values ('Morar-Dicki', 'Paôy Pêt', 1, 'ACC');
insert into Schools (name, location, division, conference) values ('Jast, Blick and Simonis', 'Sukpak', 3, 'A-10');
insert into Schools (name, location, division, conference) values ('Runolfsdottir-Russel', 'Kalynivka', 2, 'WCC');
insert into Schools (name, location, division, conference) values ('Kunze, Anderson and Hauck', 'Billa', 2, 'A-10');
insert into Schools (name, location, division, conference) values ('Ruecker Group', 'Malá Strana', 1, 'AAC');
insert into Schools (name, location, division, conference) values ('Schaefer, Dicki and Blick', 'Ciilat', 1, 'SEC');
insert into Schools (name, location, division, conference) values ('Bahringer Group', 'Mělník', 3, 'Big Ten');
insert into Schools (name, location, division, conference) values ('McClure, Osinski and Bahringer', 'Cayambe', 1, 'Mountain West');
insert into Schools (name, location, division, conference) values ('Rau-McClure', 'Libofshë', 1, 'Pac-12');
insert into Schools (name, location, division, conference) values ('Breitenberg-Abbott', 'Xinan', 2, 'Big East');
