INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 1, 1, "Spurs");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 298, 2, "Lakers");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 20, 3, "Celtics");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 32, 4, "Bulls");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 443, 5, "Magic");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 55, 6, "Timberwolves");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 634, 7, "Trail Blazers");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 71, 8, "Warriors");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 812, 9, "Kings");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 998, 10, "Hornets");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 103, 11, "Pistons");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 118, 12, "Nuggets");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 121, 13, "Hawks");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (1, 134, 14, "Mavericks");

INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 1, 1, "Spurs");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 298, 2, "Lakers");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 698, 3, "Celtics");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 98, 4, "Bulls");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 400, 5, "Magic");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 56, 6, "Timberwolves");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 6, 7, "Trail Blazers");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 79, 8, "Warriors");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 876, 9, "Kings");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 912, 10, "Hornets");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 109, 11, "Pistons");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 110, 12, "Nuggets");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 125, 13, "Hawks");
INSERT INTO Draft_Pick (draft_board_id, player_id, pick_number, team) VALUES (2, 132, 14, "Mavericks");